"""Snaphots for the inline-snapshot pytest plugin."""

from inline_snapshot import external, snapshot

snapshots_signatures = snapshot(
    {
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("907fae69658a*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("2ff981bb88e4*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("beeaa9805df1*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("a52cebb93d24*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("9d2c71bb82cc*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("8e8a2585c926*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("59d475fe0f16*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("79db258df654*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("d99481b36b65*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("27faa7df0d9e*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("d1e26a2b0132*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("7a16ce4090d6*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("0e97c16a7bed*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("139d932fa1cb*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("42201298ff23*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("7262dcd4b6de*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("a3ddc9453aa0*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("babf696c0d2c*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("27e641954226*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("7adc3150c95a*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("224b88818893*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("6c2ab955d31e*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("4e8a6f23be18*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("406e0d463ce9*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("6533f92bc276*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("19687a81cb5e*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("e03b01472366*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("d0274caf2cda*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("71e91c55e055*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("12178fe4cfea*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("8892e84d5938*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("14478e67607e*.html"),
    },
)

snapshots_members = snapshot(
    {
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("52eb2e909ab7*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("5a031d36427a*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("62650c38ed1c*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("e1fae8fc3c92*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("2d5934378085*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("780948525c0e*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("c5099c45bbfd*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("f2c00d04a3ef*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("f3d356cfc0b5*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("14286690444d*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("8ad5920c7d4a*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("2bed21548693*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("4146906386e1*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("5a55a19ef860*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("380aecd9cd71*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("031c579ed0f8*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("794a274b40a4*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("6d7e33c658cd*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("993862e3c436*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("c892d02f7f10*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("c695dedfad31*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("7e8f5917b457*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("0d55d37c7e0f*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("627d12ca5e9f*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("084cb10d7512*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("404e62875d59*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("f9881a4b86a8*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("c235590d2c03*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("43b9c19af0fb*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("97cf66d1213d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("ef53de0b0186*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("3ea7ca7ed95c*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("97281277a31d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("3c124e933c80*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("70e562d642d8*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("1dc92c49816c*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("6069ed657dd4*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("c9347797fc18*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("5b8269774dc7*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("8f102fc37560*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("3293b972c183*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("313961a121c4*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("2b64a110b933*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("bd80023e0d4b*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("8fcfb0078c66*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("218f2d654f87*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("5d4a6241d82d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("eb7b842a689a*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("1a63ff7a1545*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("1776f0412092*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("4f28331074b1*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("78e946221764*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("03182008a10c*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("e207b63a91b0*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("4dc6aeb765aa*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("2a5889b3b55e*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("b31d84bd7fc6*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("59f84e04a90a*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("b6f9e5f455ab*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("7fb7be8319c8*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("ac8e8ddcef23*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("c3060f9ccbb2*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("aa2ef2cfec19*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("5740d4cb861b*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("230f8c70c036*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("c03728330e8d*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("8d200f96beed*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("6f0185f7b1e8*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("5373328faae9*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("f9dc9ad606c3*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("cd48d88a9f88*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("58ca53cd0760*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("c2e0ee4cb94c*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("7873db4a026a*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("99deb37d28fa*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("705a3ad37d20*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("8162b9927c08*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("5c3f0918cdb7*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("e8e93fed54d0*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("a50c980055c4*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("3229c4e91652*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("0efdbc7af5e5*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("9a8327ace8c2*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("644c33875100*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("ee1429192a1a*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("4381047f5b06*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("57458bdc7eef*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("6f53dd169c6b*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("e664b263cd5f*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("87308f7c1399*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("ee25f91eef57*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("88cc6326cc7a*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("77a65b827727*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("daf985441f98*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("95dcbf3be1ed*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("de7407b2e017*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("ff1ae97397c3*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("2d2564720424*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("c0995d6b098e*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("fb4a4e985e59*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("33cd584df3ff*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("7f64fa8f5a42*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("69d69b5fca41*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("b7118aaecdca*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("c188a8b48ec5*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("a8a0953e41d3*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("a62ffbd17245*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("52f1907f2c79*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("f415dde59a79*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("7a9798ff92da*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("ca3713eddc6c*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("5b1c2127f69a*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("2305e315349a*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("6c73afa4ea43*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("d10fd3a227ed*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("20e56b5866d2*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("005d3f072a00*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("d25d9ddc3446*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("89f058eff35b*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("3dfc279bb9ed*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("5d74e76e9f2b*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("edfb52ed9c01*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("bfb66d6867c0*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("294f75bbd4c7*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("85bfca1ccda3*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("701936b8ccdc*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("6645a35521cc*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("23209ab4cd9d*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("c89e699420ab*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("f221c4ba82fa*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("d62e38d98b1b*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("e20b432dc036*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("a7c3d2ca50f6*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("5dd9f05735b9*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("fc4a14b5a6aa*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("c3f69852639d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("7046411eca2f*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("fae202502427*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("f2954fce76c2*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("3340c2170f02*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("add8c56dc8aa*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("dc8bbfba8aa3*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("4292bd9db81a*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("21b98b7c8f5b*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("c75b1a6212b0*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("2427420ad65c*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("e1aaec10e492*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("ab767016648d*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("2fadf8b4c13f*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("7553ab8e8fda*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("9e3fae7a840b*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("0b8d03f19786*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("34ff3cf6ba98*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("5b819833fc31*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("fd8c2b69c6dc*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("686675aa5501*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("f9d5650d3aa9*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("452bf4bd38d3*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("f9854345d0e9*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("631c9e94cb81*.html"),
    },
)
