"""Snaphots for the inline-snapshot pytest plugin."""

from inline_snapshot import external, snapshot

snapshots_signatures = snapshot(
    {
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("61b2bac13e58*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("e8f756d7a4c8*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("6db0416acc3b*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("eaa3424cfa34*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("56d254d72628*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("882bef68e1fc*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("9aa55138e0b3*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("1e5c16749379*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("223069d701cd*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("d8484a096ee9*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("74295839e184*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("f6a0f231f4af*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("119396e59438*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("dbcdb487d53d*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("16ee506c331b*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("576b9a1f4725*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("4f194e8f7dff*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("77aaac138a2b*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("f4a07319d0be*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("c778d3b39568*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("5261c8ae995e*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("84f9faa6b9bf*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("b1b5194a5c82*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("c1e5439eae00*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("6889f1ac806a*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("8687460e66c5*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("0b5b93dbcf90*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("3f0a546ed6b7*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", False),
            ("signature_crossrefs", True),
        ): external("441d6d669df7*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", True),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", False),
        ): external("a2b574f7545b*.html"),
        (
            ("annotations_path", "source"),
            ("separate_signature", True),
            ("show_signature", False),
            ("show_signature_annotations", False),
            ("signature_crossrefs", False),
        ): external("a6fcdb53d89f*.html"),
        (
            ("annotations_path", "brief"),
            ("separate_signature", False),
            ("show_signature", True),
            ("show_signature_annotations", True),
            ("signature_crossrefs", True),
        ): external("e65ac9d0e8c2*.html"),
    }
)

snapshots_members = snapshot(
    {
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("6d7e33c658cd*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("230f8c70c036*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("67e1d144d01d*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("de7407b2e017*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("5373328faae9*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("c235590d2c03*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("ddfe4b80f340*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("6e072fffa82c*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("c7c37bc34df2*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("78e946221764*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("858d6172bbc0*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("28273a409c99*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("7553ab8e8fda*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("93dfd61e0d51*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("99deb37d28fa*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("f2c00d04a3ef*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("f9dc9ad606c3*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("03182008a10c*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("54ddcea31494*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("c03728330e8d*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("39b1ae425232*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("ee25f91eef57*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("627d12ca5e9f*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("6c17d7ae4a4a*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("23209ab4cd9d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("dc8bbfba8aa3*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("745607cca149*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("3c0b7acc38c7*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("780948525c0e*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("33cd584df3ff*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("6a7cf9110975*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("01ba77af1ed9*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("466ab09ac219*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("2d2564720424*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("9ca1553176c1*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("b31d84bd7fc6*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("1ae144e025fa*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("2427420ad65c*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("701936b8ccdc*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("4146906386e1*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("69d69b5fca41*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("bd80023e0d4b*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("aeaa7fef156f*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("794a274b40a4*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("b75ea99e385c*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("e1aaec10e492*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("43b9c19af0fb*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("daf985441f98*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("b7118aaecdca*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("5dd9f05735b9*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("3ea7ca7ed95c*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("686675aa5501*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("89b25b72ed0d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("73499d4f28ce*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("0e3e602c7816*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("993862e3c436*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "source"),
        ): external("f9d5650d3aa9*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("f9881a4b86a8*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("380aecd9cd71*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("2a5889b3b55e*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("f48aff73c47f*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "source"),
        ): external("974bb0a57c74*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("c89e699420ab*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("fc4a14b5a6aa*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("d8345b1fc1ab*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("0d55d37c7e0f*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("ab767016648d*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("3ef7d09f9510*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("5b819833fc31*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("c2e0ee4cb94c*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("5b1c2127f69a*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("50dddaaa96ff*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("320904ab4dac*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("23fc232df798*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("a7c3d2ca50f6*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("7c49f69d4563*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("ccf0b99e1be0*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("88cc6326cc7a*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("c9347797fc18*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("3293b972c183*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("c0995d6b098e*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("52eb2e909ab7*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("9a8327ace8c2*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("eb7b842a689a*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("2fadf8b4c13f*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("404e62875d59*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("0849da7a0171*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("5d4a6241d82d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("c695dedfad31*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("5c49e586e0cd*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("a50c980055c4*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("f9854345d0e9*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("aa97ee9f2502*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("031c579ed0f8*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("e20b432dc036*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("8b6e71cbbd6b*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("e8bdb82acc98*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("97abb4cb35ba*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("f221c4ba82fa*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("f91a6ee00766*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("6645a35521cc*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("fdda69855b91*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("313961a121c4*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("3340c2170f02*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("9080ca97c9ed*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("3c124e933c80*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("ae0935ebf3fe*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("9a667297d92e*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("1dc92c49816c*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("c314982b01b1*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("bfb66d6867c0*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("7fb7be8319c8*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("5c3f0918cdb7*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("8d200f96beed*.html"),
        (
            ("filters", None),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "source"),
        ): external("1cbc61bd75c6*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("9e3fae7a840b*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("21b98b7c8f5b*.html"),
        (
            ("filters", ()),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "source"),
        ): external("8f102fc37560*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("52f1907f2c79*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("55219a3d318d*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("5d74e76e9f2b*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("1776f0412092*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", None),
            ("members_order", "source"),
        ): external("aedfff3e7e59*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("7eb3ae6b5549*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("20773832788d*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "source"),
        ): external("4c4a858ac10b*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("ddb32ae05fa6*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("005d3f072a00*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("5b8269774dc7*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("3dfc279bb9ed*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ()),
            ("members_order", "source"),
        ): external("ee1429192a1a*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "alphabetical"),
        ): external("cd48d88a9f88*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "alphabetical"),
        ): external("ac8e8ddcef23*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("22c1785ce54d*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("be00916ce887*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("ad06725aef99*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("705a3ad37d20*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("f415dde59a79*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("2b64a110b933*.html"),
        (
            ("filters", None),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("c85110e8daa5*.html"),
        (
            ("filters", None),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("378da98c9162*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("aabb75819a37*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", ()),
            ("members_order", "source"),
        ): external("89f058eff35b*.html"),
        (
            ("filters", ()),
            ("inherited_members", True),
            ("members", ()),
            ("members_order", "source"),
        ): external("d10fd3a227ed*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("5740d4cb861b*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", False),
            ("members_order", "source"),
        ): external("0efdbc7af5e5*.html"),
        (
            ("filters", ()),
            ("inherited_members", ("a", "b")),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("70e562d642d8*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", True),
            ("members", None),
            ("members_order", "source"),
        ): external("04da9ce1a4da*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("6f53dd169c6b*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", False),
            ("members_order", "source"),
        ): external("5a55a19ef860*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ()),
            ("members", None),
            ("members_order", "alphabetical"),
        ): external("8fb19d9706fb*.html"),
        (
            ("filters", None),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("25c546b9560d*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", None),
            ("members_order", "source"),
        ): external("f3bf6acf915a*.html"),
        (
            ("filters", ()),
            ("inherited_members", ()),
            ("members", True),
            ("members_order", "source"),
        ): external("69259b939451*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "alphabetical"),
        ): external("644c33875100*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", ("a", "b")),
            ("members_order", "source"),
        ): external("20e56b5866d2*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", True),
            ("members", False),
            ("members_order", "source"),
        ): external("fb4a4e985e59*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "source"),
        ): external("882e9756e994*.html"),
        (
            ("filters", ("a",)),
            ("inherited_members", ("a", "b")),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("cd7e8083c570*.html"),
        (
            ("filters", ("!a",)),
            ("inherited_members", False),
            ("members", True),
            ("members_order", "alphabetical"),
        ): external("b86c9933f03c*.html"),
    }
)
